# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [37]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config())

1.17.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [6]:
n = np.zeros(10)
print("%d bytes" % (n.size * n.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help(<class_name>.<function_name>)

SyntaxError: invalid syntax (<ipython-input-7-6b0b7642fd08>, line 1)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
n=np.zeros(10)
n[4]=1
print(n)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
import numpy as np
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
print(np.arange(10,50)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [14]:
arr=[1,2,0,0,4,0]

t = np.transpose(np.nonzero(arr)) 
print(t)

[[0]
 [1]
 [4]]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.rand(3,3,3)

array([[[0.33861829, 0.59245117, 0.27219003],
        [0.02602853, 0.56627171, 0.91682297],
        [0.56043992, 0.2405732 , 0.77875074]],

       [[0.15764592, 0.32360083, 0.34216262],
        [0.39790956, 0.16982006, 0.52856897],
        [0.57784047, 0.71843315, 0.53191891]],

       [[0.2713241 , 0.7912121 , 0.21582283],
        [0.12470531, 0.82528215, 0.04946092],
        [0.62988288, 0.27946376, 0.69489383]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [11]:
arr=np.random.rand(3,3,3)
print(np.amax(arr))
np.amin(arr)


0.9909844183443334


0.10752050049350714

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
arr=np.random.rand(30)
print("Mean Value:",arr.sum()/30)

Mean Value: 0.5013327574458012


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [20]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array:")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
print(np.pad(x,1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
dia = np.diag(1+np.arange(4),k=-1)
print(dia)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [36]:
x=np.zeros((8,8))
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [74]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [40]:
print(np.tile(np.array([[0,1],[1,0]]),(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [41]:
z = np.random.random(( 5 , 5 )) 
zs = (z - z.mean ()) / z.std () 
print (zs)

[[-1.63977456  1.09964263  0.27277335  1.33187219 -0.71924006]
 [-0.84770032  1.33680449 -1.52327108  0.66511978  0.80741335]
 [ 1.09248868  1.4490108   0.42622653 -0.83950287  1.31550154]
 [-1.09743099  0.48592828 -0.84188722 -0.34787532 -0.38214085]
 [-1.77552694  0.59794767  0.39948439 -0.72977281 -0.53609066]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [75]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

c:\users\dhananjay\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [46]:
print(np.ones((5,3))@np.ones((3,2)))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [52]:
x=np.arange(11)

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
array([-2.14748365e+09])


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
round()

#### 30. How to find common values between two arrays? (★☆☆)

In [62]:
x=np.array([1,2,4,6])
y=[1,3,4]
print("Common values between two arrays:")
print(np.intersect1d(x,y))

Common values between two arrays:
[1 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [76]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
no

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [69]:
import datetime
print('Yesterday : ',datetime.date.today() - datetime.timedelta(days = 1))
print('Today : ',datetime.date.today())
print('Tomorrow : ',datetime.date.today() + datetime.timedelta(days = 1))

Yesterday :  2019-10-12
Today :  2019-10-13
Tomorrow :  2019-10-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [70]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [77]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [73]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[7. 3. 8. 4. 7. 7. 5. 0. 9. 3.]
[7. 3. 8. 4. 7. 7. 5. 0. 9. 3.]
[7. 3. 8. 4. 7. 7. 5. 0. 9. 3.]
[7 3 8 4 7 7 5 0 9 3]
[7. 3. 8. 4. 7. 7. 5. 0. 9. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [78]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [81]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(z)

[[0.11085835 0.84745508 0.62511976 0.90989885 0.35837914]
 [0.3238377  0.91122509 0.14218475 0.73061705 0.7688781 ]
 [0.84553147 0.94139603 0.66638149 0.3260419  0.90549698]
 [0.25668809 0.68243459 0.32540077 0.4582347  0.44902111]
 [0.07435614 0.71255527 0.65919085 0.35554701 0.40762583]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [84]:
print(np.linspace(0,1,11,endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [85]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.21459926 0.37134644 0.41721577 0.43221703 0.57404227 0.60118051
 0.61704773 0.65312348 0.90351579 0.93363405]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [86]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [87]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [95]:
Z = np.zeros(10)
Z.flags.writeable = False
Z = 1
print(z)

[[0.11085835 0.84745508 0.62511976 0.90989885 0.35837914]
 [0.3238377  0.91122509 0.14218475 0.73061705 0.7688781 ]
 [0.84553147 0.94139603 0.66638149 0.3260419  0.90549698]
 [0.25668809 0.68243459 0.32540077 0.4582347  0.44902111]
 [0.07435614 0.71255527 0.65919085 0.35554701 0.40762583]]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [96]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.08221208 0.95693271 0.98878278 1.05597424 0.65934427 0.40380107
 0.21472589 0.21296028 0.78371411 0.83089866]
[0.57209025 0.60570818 1.46412657 0.61057801 1.14972805 0.82937448
 0.24825321 1.11738606 1.17422593 0.95077238]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [99]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.55253809 0.2737776  0.09566916 0.         0.95440616 0.32315091
 0.68940627 0.61449111 0.78147292 0.97556049]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [98]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [100]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [101]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [106]:
np.set_printoptions(threshold=0)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [116]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

16


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [117]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


c:\users\dhananjay\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [118]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.36903944 0.35385173 ... 0.65972788 0.38965668 0.22299138]
 [0.36903944 0.         0.34078873 ... 0.49948736 0.73452786 0.33767069]
 [0.35385173 0.34078873 0.         ... 0.31250047 0.54775002 0.13645287]
 ...
 [0.65972788 0.49948736 0.31250047 ... 0.         0.83502894 0.44880198]
 [0.38965668 0.73452786 0.54775002 ... 0.83502894 0.         0.43832175]
 [0.22299138 0.33767069 0.13645287 ... 0.44880198 0.43832175 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [119]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 ... 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [121]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

[[0.11085835 0.84745508 0.62511976 0.90989885 0.35837914]
 [0.3238377  0.91122509 0.14218475 0.73061705 0.7688781 ]
 [0.84553147 0.94139603 0.66638149 0.3260419  0.90549698]
 [0.25668809 0.68243459 0.32540077 0.4582347  0.44902111]
 [0.07435614 0.71255527 0.65919085 0.35554701 0.40762583]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [123]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [124]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [125]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [127]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(y)

[1, 3, 4]


#### 59. How to sort an array by the nth column? (★★☆)

In [128]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 3 6]
 [7 1 9]
 [1 1 8]]
[[7 1 9]
 [1 1 8]
 [7 3 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [129]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [130]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.47129084423493783


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [131]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [132]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [134]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[2. 2. 2. ... 2. 2. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [135]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. ... 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [136]:

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))


[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [137]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[65 46 52 60]
 [48 61 45 58]
 [41 47 47 55]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [138]:

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.52964667 0.4821714  0.45241792 ... 0.61051571 0.36478152 0.46600567]


#### 69. How to get the diagonal of a dot product? (★★★)

In [140]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
x=np.diag(np.dot(A, B))
print(x)

[0.69858867 1.86400261 0.96988195 1.09387039 1.23672986]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [141]:
Z = np.array([1,2,3,4,5])
nz = 3
Z2 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z2[::nz+1] = Z
print(Z2)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [142]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [143]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [144]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 49) ( 3, 86) ( 4, 20) ... (59, 92) (78, 94) (93, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [145]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 ... 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [153]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 ...
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [147]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

[16.07038004 13.35057033  5.89693504 ...  4.50652649  0.34326254
  3.52041857]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [152]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.74267926  0.1879808  10.47876134 ... 12.32585252  1.6974411
  0.10052738]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [151]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.31178121  4.46891598  0.19781691 ... 11.17846251  0.72149047
   3.51968367]
 [ 2.44989487  1.67888281  2.13741394 ... 12.18623793  6.37674779
   2.16393737]
 [17.31915798 11.49972343  1.02422866 ...  7.7034364   6.06246031
   2.13877513]
 ...
 [ 9.1694864   2.2054589   1.77741082 ... 13.60100226  3.08311302
   5.60986752]
 [ 1.17361224  2.4604501  10.91464743 ...  3.81596505  1.52108753
   6.63146451]
 [ 2.69371952  0.25016778 13.20938459 ...  2.95973779  3.38826888
   8.65689411]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [155]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [156]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [157]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 2]
   [3 3 2]
   [2 1 4]]

  [[0 2 2]
   [3 2 3]
   [1 4 3]]

  [[2 2 2]
   [2 3 3]
   [4 3 4]]

  ...

  [[1 4 4]
   [4 2 1]
   [3 1 3]]

  [[4 4 1]
   [2 1 4]
   [1 3 1]]

  [[4 1 1]
   [1 4 4]
   [3 1 0]]]


 [[[3 3 2]
   [2 1 4]
   [1 1 0]]

  [[3 2 3]
   [1 4 3]
   [1 0 4]]

  [[2 3 3]
   [4 3 4]
   [0 4 1]]

  ...

  [[4 2 1]
   [3 1 3]
   [2 2 2]]

  [[2 1 4]
   [1 3 1]
   [2 2 1]]

  [[1 4 4]
   [3 1 0]
   [2 1 4]]]


 [[[2 1 4]
   [1 1 0]
   [1 1 0]]

  [[1 4 3]
   [1 0 4]
   [1 0 1]]

  [[4 3 4]
   [0 4 1]
   [0 1 3]]

  ...

  [[3 1 3]
   [2 2 2]
   [4 0 4]]

  [[1 3 1]
   [2 2 1]
   [0 4 0]]

  [[3 1 0]
   [2 1 4]
   [4 0 3]]]


 ...


 [[[3 4 4]
   [4 4 3]
   [0 2 3]]

  [[4 4 1]
   [4 3 3]
   [2 3 4]]

  [[4 1 4]
   [3 3 3]
   [3 4 1]]

  ...

  [[0 2 4]
   [0 4 0]
   [4 2 0]]

  [[2 4 1]
   [4 0 4]
   [2 0 4]]

  [[4 1 0]
   [0 4 0]
   [0 4 0]]]


 [[[4 4 3]
   [0 2 3]
   [0 1 4]]

  [[4 3 3]
   [2 3 4]
   [1 4 3]]

  [[3 3 3]
   [3 4 1]
   [4 3 1]]

  ...

  [[0

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [158]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 ...
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [159]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [160]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [162]:
arrays = ([1, 2, 3], [4, 5], [6, 7])
arrays = [np.asarray(a) for a in arrays]
shape = (len(x) for x in arrays)

ix = np.indices(shape, dtype=int)
ix = ix.reshape(len(arrays), -1).T

for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]
print(ix)

[[1 4 6]
 [1 4 7]
 [1 5 6]
 ...
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [163]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [165]:
x = np.random.rand(int(5e7))

np.power(x,3)
x*x*x
np.einsum('i,i,i->i',x,x,x)

array([0.00665974, 0.36222071, 0.04373397, ..., 0.24467077, 0.01224627,
       0.08512932])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [166]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 ... 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [167]:
Z = np.random.randint(0,5,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 2 0]
 [4 4 4]
 [0 4 4]
 ...
 [1 4 2]
 [0 2 1]
 [2 0 3]]
[[3 2 0]
 [0 4 4]
 [3 0 1]
 ...
 [1 4 2]
 [0 2 1]
 [2 0 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [168]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [169]:
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 2]
 [0 2 1]
 [0 4 4]
 ...
 [3 2 0]
 [3 2 4]
 [4 4 4]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [170]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.1091958 , 0.43072604, 0.15412862, ..., 0.03114192, 0.31093177,
        0.0916918 ],
       [0.01927526, 0.07603182, 0.0272068 , ..., 0.00549718, 0.05488572,
        0.01618545],
       [0.02058116, 0.08118298, 0.02905007, ..., 0.00586961, 0.05860423,
        0.01728201],
       ...,
       [0.09235572, 0.36429986, 0.13035904, ..., 0.02633925, 0.26298016,
        0.07755117],
       [0.13004242, 0.51295615, 0.18355338, ..., 0.03708724, 0.37029191,
        0.10919673],
       [0.02040423, 0.0804851 , 0.02880034, ..., 0.00581915, 0.05810044,
        0.01713345]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)